apiVersion: apps/v1

kind: Deployment

metadata: 
  name: dbappdeploy
  labels:
    app: db

spec:
  replicas: 2

  selector:
    matchLabels:
      app: db
    
  template:
    metadata:
      name: dbpod
      labels:
        app: db

    spec: 
      containers:
        - image: postgres:15-alpine
          name: postgresdb
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              name: postgres
