apiVersion: v1
kind: Service

metadata:
  name: dbservice
  labels:
    app: db

spec:
  type: ClusterIP
  ports:
    - name: "db-service"
      targetPort: 5432
      port: 5432

  selector:
    app: db