apiVersion: v1
kind: Service

metadata:
  name: redisservice
  labels:
    app: redis

spec:
  type: ClusterIP
  ports:
    - name: "redis-service"
      targetPort: 6379
      port: 6379

  selector:
    app: redis