apiVersion: v1
kind: Service

metadata:
  name: resultsservice
  labels:
    app: results

spec:
  type: NodePort
  ports:
    - name: "results-service"
      targetPort: 80
      port: 8081
      nodePort: 31001

  selector:
    app: results