apiVersion: v1
kind: Service

metadata:
  name: voteservice
  labels:
    app: vote

spec:
  type: NodePort
  ports:
    - name: "vote-service"
      targetPort: 80
      port: 8080
      nodePort: 31000

  selector:
    app: vote